name: folio
description: Devfolio escrito no flutter.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.2+112

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

# Animations
  animations: ^2.0.11   

# Google Fonts
  google_fonts: ^6.2.1

# Google Maps
  google_maps_flutter: ^2.10.0

# Material Icons
  material_design_icons_flutter: 5.0.5955-rc.1

# Shared Preferences
  shared_preferences: ^2.3.5

# Shimer
  shimmer: ^3.0.0

# Url Launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

