name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.2'

    - name: Install dependencies
      run: flutter pub get

    - name: Build web
      run: flutter build web --release

    - name: Deploy to GitHub Pages
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        rm -rf docs
        mv build/web docs
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add docs
        git commit -m "Deploy to GitHub Pages"
        git push https://github.com/hendrilmendes/Wally.git HEAD:main
